"""zettel_parser: A parser for a custom variant of Org-mode."""

from zettel_parser import common_regex, first_pass, inline_pass, structure_pass
from zettel_parser.first_pass import parse_first_pass
from zettel_parser.first_pass_elements import (
    Block,
    CheckboxState,
    FileTags,
    FirstPassElement,
    LatexBlock,
    LatexBlockType,
    NodeProperty,
    PropertyDrawer,
    Title,
)
from zettel_parser.inline_pass import (
    Bold,
    Code,
    Emphasis,
    InlineLatex,
    InlinePart,
    Italic,
    Link,
    StrikeThrough,
    Underline,
    Verbatim,
    parse_inline,
)
from zettel_parser.structure_pass import (
    BlankLines,
    FlatText,
    FlatTextPart,
    Headline,
    List,
    ListItem,
    ListPart,
    Node,
    Paragraph,
    ParagraphPart,
    ParagraphText,
    Zettel,
    parse,
)

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "BlankLines",
    "Block",
    "Bold",
    "CheckboxState",
    "Code",
    "Emphasis",
    "FileTags",
    "FirstPassElement",
    "FlatText",
    "FlatTextPart",
    "Headline",
    "InlineLatex",
    "InlinePart",
    "Italic",
    "LatexBlock",
    "LatexBlockType",
    "Link",
    "List",
    "ListItem",
    "ListPart",
    "Node",
    "NodeProperty",
    "Paragraph",
    "ParagraphPart",
    "ParagraphText",
    "PropertyDrawer",
    "StrikeThrough",
    "Title",
    "Underline",
    "Verbatim",
    "Zettel",
    "common_regex",
    "first_pass",
    "inline_pass",
    "structure_pass",
    "parse",
    "parse_first_pass",
    "parse_inline",
]
